### ISSUE TITLE
alternative: search http://leginfo.legislature.ca.gov/ directly

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#10]
if open states is too limited. We should try to directly search http://leginfo.legislature.ca.gov/ . 

@taivy Please also take a look at this option. Let me know if this is something you are interested in doing. Thanks!

**Comment by liaosvcaf** [comment]
https://openstates.org/ca/bills/ also offers full text search. We can use python or other language to search for key words.

**Comment by taivy** [comment]
@liaosvcaf

Comparing openstates.org and leginfo.legislature.ca.gov the last seems best

openstates.org is slower than leginfo.legislature.ca.gov
When I search "Education" on Openstate I get 373 bills, on leginfo.legislature.ca.gov I get 755

But OpenState views search results better (there is subject and latest action). On leginfo.legislature.ca.gov we get only bills identifier

https://openstates.org/ca/bills/?query=education&session=&classification=&sponsor=&page=1

http://leginfo.legislature.ca.gov/faces/billSearchClient.xhtml?session_year=20192020&keyword=education&house=Both&author=All&lawCode=All

Fetching all laws from search results might take a lot of time. But we can fetch only first few pages and fetch other only if user goes to next page. Or we can make a database and update

**Comment by liaosvcaf** [comment]
I think you have the freedom to choose a solution you feel comfortable
with, as long as you reach the project goal.

Thanks.

**Comment by liaosvcaf** [comment]
Looks like this this the solution right now.
