### ISSUE TITLE
source comments or readme for parsing_fncs_for_db.py

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#13]
@taivy I merged this script.  Could you please add some source code comments or a readme file to describe what it does (e.g. input and output) ?   Does it complete the first milestone (backend for API) ?  Thanks!

**Comment by taivy** [comment]
parsing_fncs_for_db.py contains functions for parsing laws and saving them to SQLite database. It does nothing (I mean, it's functions. These functions are not necessary for the web app, they are only for creating the database. 

Main function is parse_laws_into_db, which takes search params, makes query on site, parses bills and saves them to database
Function has comments and params description
