### ISSUE TITLE
fix the order of bills in the result page

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#18]
Another thing is the display of bills is not really based on last action date (LAD). The first bill now has 2019-09-28 as LAD. The 4th entry has 2019-07-08.

**Comment by taivy** [comment]
@liaosvcaf 

#20

**Comment by liaosvcaf** [comment]
@taivy It seems the order for one page is right from 2019 to 2017. But for next page, it restarts from 2019 to 2017. I was expecting to have all pages ordered uniformly from most recent date to oldest date.  Could you please check this again?
![image](https://user-images.githubusercontent.com/51533973/63239892-31a30080-c202-11e9-947e-f78b98a83605.png)

![image](https://user-images.githubusercontent.com/51533973/63239897-3a93d200-c202-11e9-9ba8-f9fb8b6f6c0d.png)

**Comment by taivy** [comment]
> 
> 
> @taivy It seems the order for one page is right from 2019 to 2017. But for next page, it restarts from 2019 to 2017. I was expecting to have all pages ordered uniformly from most recent date to oldest date. Could you please check this again?

Fixed in #20

**Comment by liaosvcaf** [comment]
The order seems fixed in latest version
