### ISSUE TITLE
test email notifications on the test server

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#41]
http://13.209.125.34/subscribe

After typing in an email and keyword, I got the following error message:

![image](https://user-images.githubusercontent.com/51533973/76169639-7dce7780-6137-11ea-8099-b7490272e676.png)

**Comment by liaosvcaf** [comment]
I tried to change the site URL to the correct one. I also used the gmail account link to log in. I still got the same error message.

**Comment by taivy** [comment]
When error appears, you should confirm on https://accounts.google.com/b/0/DisplayUnlockCaptcha (from any device)

For some reason it may not work at first or second time. So you may need to confirm and reload the page several times. 

If  you use new account (not california.bills.notifier.bot@gmail.com) you'll also need to enable this https://myaccount.google.com/lesssecureapps

**Comment by liaosvcaf** [comment]
This seem to be working now. Thanks!
