### ISSUE TITLE
instruction for elasticsearch auto start on booting does not work 

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#48]
The instruction is: 

Start elasticsearch service Use the update-rc.d command to configure Elasticsearch to start automatically when the system boots up:

sudo update-rc.d elasticsearch defaults 95 10

I tried this on 13.209.125.34 .  The service is not started automatically whenever I reboot the machine. 

```
ubuntu@ip-172-31-24-70:~$ sudo service elasticsearch status -l
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: http://www.elastic.co
```

Could you please double check the instruction (and test it on the test server)?

**Comment by taivy** [comment]
Yes, instruction is correct. It's from official Elasticsearch documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/starting-elasticsearch.html#start-es-deb-init

But there's another command to do it: https://www.elastic.co/guide/en/elasticsearch/reference/current/starting-elasticsearch.html#start-es-deb-systemd

Updated instruction to include this another command

but "inactive (dead)" most probably means that ES failed to start. Check your logs

**Comment by taivy** [comment]
Readme is updated by #49

**Comment by liaosvcaf** [comment]
The alternative way works. Thanks.
