### ISSUE TITLE
move all files into $HOME/.svcaf

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#51]
These files are frequently updated after deployment.
     modified:   bills.db
        modified:   keywords.txt
        modified:   notifications.log
        modified:   subscribed_emails.txt

Please move them to $HOME/.svcaf , and change the paths in your python scripts.
So git pull will cleanly update the local repo.

**Comment by liaosvcaf** [comment]
@taivy please take a look. thanks.

**Comment by taivy** [comment]
I think adding them to .gitignore would be better
